// Service worker: message routing, on-demand
// injection for "Fill this page" on non-ATS sites.

import { Msg, PageContext } from '../lib/messaging'
import * as store from '../lib/store'
import { BankAnswer, PendingQuestion, ResumeVariant, jobUrlKey, roleCompanyLabel, uid } from '../lib/types'
import { applyIntakeFacts } from '../lib/profileMerge'
import { normalizeQuestion, similarity } from '../lib/questions'
import { cloudFillAssist, cloudResumeIntake, polishAnswer, runQuickScore, runTailorCv } from '../ai/run'
import { renderResumePdf } from '../pdf/resumePdf'
import { pullFromCloud, startCloudMirror } from './cloudMirror'
// CRXJS: gives us the emitted content-script path for scripting.executeScript.
import contentScriptPath from '../content/index.ts?script'

chrome.runtime.onInstalled.addListener(() => {
  void chrome.sidePanel.setPanelBehavior({ openPanelOnActionClick: true })
  // Unanswered questions used to show as a count on the toolbar icon. They
  // now live on one tab inside Profile, which is the only place that number
  // means anything. Clear any badge a previous version left behind.
  void chrome.action.setBadgeText({ text: '' })
})

// Mirror local data to the signed-in account; load the account's data
// whenever the worker wakes.
startCloudMirror()
void pullFromCloud().catch((e) => console.error('[shortlisted] cloud load failed:', e))

/**
 * The emitted content-script file. The build-time `?script` import is a
 * content-hashed name, so a service worker left over from an earlier build
 * asks for a file that no longer exists ("Could not load file"). The manifest
 * is regenerated by the same build, so reading the path from it at runtime is
 * always in step with what's actually on disk; the import stays as a fallback.
 */
function contentScriptFiles(): string[] {
  const fromManifest = chrome.runtime.getManifest().content_scripts?.flatMap((cs) => cs.js ?? []) ?? []
  return fromManifest.length ? [...new Set(fromManifest)] : [contentScriptPath]
}

async function injectContentScript(tabId: number): Promise<void> {
  await chrome.scripting.executeScript({
    target: { tabId, allFrames: true },
    files: contentScriptFiles(),
  })
}

chrome.runtime.onMessage.addListener((msg: Msg, sender, sendResponse) => {
  // sidePanel.open() only works while the click's user-gesture token is
  // alive, and that token dies at the first await — so panel-opening
  // messages are handled HERE, synchronously, with the sender's window id.
  if (msg.type === 'openProfileNote' || msg.type === 'openSidePanel') {
    if (msg.type === 'openProfileNote') void store.set('pendingNav', 'tellme')
    const windowId = sender.tab?.windowId
    if (windowId !== undefined) {
      chrome.sidePanel.open({ windowId }).catch((e) => console.warn('[shortlisted] sidePanel.open failed:', e))
    }
    sendResponse({ ok: true })
    return false
  }
  handle(msg)
    .then(sendResponse)
    .catch((err) => sendResponse({ error: String(err) }))
  return true // async response
})

async function handle(msg: Msg): Promise<unknown> {
  switch (msg.type) {
    case 'getFillState': {
      const [profile, answerBank, resumes, settings] = await Promise.all([
        store.get('profile'),
        store.get('answerBank'),
        store.get('resumes'),
        store.get('settings'),
      ])
      return {
        profile,
        answerBank,
        settings,
        resumes: resumes.map(({ id, label, fileName, isDefault, tags }) => ({ id, label, fileName, isDefault, tags })),
      }
    }

    case 'getResumeData': {
      const resumes = await store.get('resumes')
      const r = resumes.find((x) => x.id === msg.resumeId)
      return r ? { base64: r.dataBase64, fileName: r.fileName } : null
    }

    // A CV uploaded straight from the on-page panel (the form asked for one
    // and the bank was empty). First CV in becomes the default.
    case 'saveResume': {
      const entry: ResumeVariant = {
        id: uid(),
        label: msg.fileName.replace(/\.pdf$/i, ''),
        fileName: msg.fileName,
        tags: [],
        isDefault: false,
        createdAt: Date.now(),
        source: 'uploaded',
        dataBase64: msg.base64,
      }
      let list: ResumeVariant[] = []
      await store.update('resumes', (resumes) => {
        entry.isDefault = resumes.length === 0
        list = [...resumes, entry]
        return list
      })
      // Tag it and fold new facts into the profile in the background.
      void intakeResume(entry.id)
      return {
        id: entry.id,
        resumes: list.map(({ id, label, fileName, isDefault, tags }) => ({ id, label, fileName, isDefault, tags })),
      }
    }

    case 'intakeResume': {
      void intakeResume(msg.resumeId)
      return { ok: true }
    }

    // "Tailor a new CV for this job" from the on-page panel: tailor against
    // the page's job text, render in the chosen template, save it to the CV
    // list (NOT as default), hand back the id so the panel can attach it.
    case 'tailorAttach': {
      const [settings, profile] = await Promise.all([store.get('settings'), store.get('profile')])
      if (!settings.accountEmail) return { error: 'Sign in first.' }
      try {
        const result = await runTailorCv(settings, profile, msg.jobText, undefined, msg.note)
        // Facts the candidate stated in their note become permanent profile
        // facts (additive) — the server already tailored WITH them.
        if (result.newFacts) {
          await store.update('profile', (p) => applyIntakeFacts(p, result.newFacts!))
        }
        const base64 = renderResumePdf(profile, result.resume, msg.templateId)
        const safe = result.resume.label.replace(/[^\w\- ]/g, '').replace(/\s+/g, '-').slice(0, 40)
        const entry: ResumeVariant = {
          id: uid(),
          label: roleCompanyLabel(result.resume.label, result.job.company),
          fileName: `${profile.identity.firstName}-${profile.identity.lastName}-${safe}.pdf`.replace(/\s+/g, '-'),
          tags: [result.job.role, result.job.company].filter(Boolean),
          isDefault: false,
          createdAt: Date.now(),
          source: 'generated',
          templateId: msg.templateId,
          dataBase64: base64,
          content: result.resume,
        }
        await store.update('resumes', (list) => [...list, entry])
        return { id: entry.id, label: entry.label }
      } catch (e) {
        return { error: e instanceof Error ? e.message : 'Tailoring failed.' }
      }
    }

    case 'saveAnswer': {
      const norm = normalizeQuestion(msg.questionRaw)
      await store.update('answerBank', (bank) => {
        const existing = bank.find((a) => a.questionNorm === norm || similarity(a.questionNorm, norm) >= 0.92)
        if (existing) {
          if (existing.answer !== msg.answer) existing.polished = undefined // stale polish dies with the old answer
          existing.answer = msg.answer
          existing.answerType = msg.answerType
          if (!existing.questionRaw.includes(msg.questionRaw)) existing.questionRaw.push(msg.questionRaw)
          existing.timesUsed += 1
          existing.lastUsedAt = Date.now()
          if (!existing.sourceJobUrls.includes(msg.jobUrl)) existing.sourceJobUrls.push(msg.jobUrl)
          return [...bank]
        }
        const fresh: BankAnswer = {
          id: uid(),
          questionNorm: norm,
          questionRaw: [msg.questionRaw],
          answer: msg.answer,
          answerType: msg.answerType,
          timesUsed: 1,
          lastUsedAt: Date.now(),
          sourceJobUrls: [msg.jobUrl],
        }
        return [...bank, fresh]
      })
      // Free-text answers get an AI polish in the background (fire and forget).
      if (msg.answerType === 'text') void polishInBackground(norm, msg.questionRaw, msg.answer)
      return { ok: true }
    }

    case 'markAnswerUsed': {
      await store.update('answerBank', (bank) =>
        bank.map((a) =>
          a.id === msg.answerId
            ? {
                ...a,
                timesUsed: a.timesUsed + 1,
                lastUsedAt: Date.now(),
                sourceJobUrls: a.sourceJobUrls.includes(msg.jobUrl) ? a.sourceJobUrls : [...a.sourceJobUrls, msg.jobUrl],
              }
            : a,
        ),
      )
      return { ok: true }
    }

    case 'capturePending': {
      await store.update('pendingQuestions', (pending) => {
        const next = [...pending]
        for (const q of msg.questions) {
          const norm = normalizeQuestion(q.questionRaw)
          const dupe = next.some((p) => normalizeQuestion(p.questionRaw) === norm)
          if (!dupe) next.push({ ...q, id: uid(), capturedAt: Date.now() } satisfies PendingQuestion)
        }
        return next
      })
      return { ok: true }
    }

    case 'resolvePending': {
      const norm = normalizeQuestion(msg.questionRaw)
      await store.update('pendingQuestions', (pending) =>
        pending.filter((p) => normalizeQuestion(p.questionRaw) !== norm),
      )
      return { ok: true }
    }

    case 'recordApplication': {
      await store.update('applications', (apps) => {
        // One record per job URL; re-clicking submit updates the timestamp.
        const existing = apps.find((a) => a.jobUrl === msg.record.jobUrl)
        if (existing) {
          existing.appliedAt = Date.now()
          // A different CV on a re-submit is the one that counts.
          if (msg.record.resumeId) existing.resumeId = msg.record.resumeId
          return [...apps]
        }
        return [...apps, { ...msg.record, id: uid(), appliedAt: Date.now(), status: 'applied' as const }]
      })
      // If this URL is in the queue, mark it applied.
      await store.update('queue', (queue) =>
        queue.map((q) => (sameJob(q.url, msg.record.jobUrl) ? { ...q, status: 'applied' as const } : q)),
      )
      return { ok: true }
    }

    // 'openSidePanel' / 'openProfileNote' are handled synchronously in the
    // onMessage listener above — sidePanel.open() must run before any await.

    case 'scoreFitPage': {
      const [settings, profile] = await Promise.all([store.get('settings'), store.get('profile')])
      if (profile.work.length === 0) return { error: 'Fill your profile first (side panel → Profile).' }
      try {
        const result = await runQuickScore(settings, profile, msg.jobText)
        await store.update('fitScores', (scores) => ({
          ...scores,
          [jobUrlKey(msg.jobUrl)]: { score: result.fit.overallScore, verdict: result.fit.verdict, at: Date.now() },
        }))
        return result
      } catch (e) {
        return { error: e instanceof Error ? e.message : String(e) }
      }
    }

    // Failures come back as codes, not sentences — the side panel owns the
    // wording so it can be shown in the user's language.
    case 'fillCurrentTab': {
      const [tab] = await chrome.tabs.query({ active: true, currentWindow: true })
      if (!tab?.id || !tab.url) return { errorCode: 'noTab' }
      if (/^(chrome|edge|about|chrome-extension|devtools|view-source):/.test(tab.url)) {
        return { errorCode: 'cannotFill' }
      }
      try {
        await injectContentScript(tab.id)
      } catch (e) {
        console.error('[shortlisted] inject failed:', e)
        return { errorCode: 'cannotFill' }
      }
      // Injecting is not enough: the script guards against double-loading, so
      // on a page where it was already running the injection is a no-op. The
      // message is what actually opens the panel and starts the fill, and only
      // frames holding a form answer it.
      try {
        const res = await chrome.tabs.sendMessage<Msg, { handled?: boolean }>(tab.id, { type: 'triggerFill' })
        return res?.handled ? { ok: true } : { errorCode: 'noForm' }
      } catch {
        // No frame answered: nothing on this page holds a form.
        return { errorCode: 'noForm' }
      }
    }

    // Read-only sibling of fillCurrentTab, for Home's context slot. It
    // deliberately does NOT inject the content script: asking what is on a page
    // must never be the thing that puts us on it. No content script means no
    // answer, which Home reads as "nothing to offer here" — the right default.
    case 'pageContext': {
      const [tab] = await chrome.tabs.query({ active: true, currentWindow: true })
      if (!tab?.id || !tab.url) return null
      if (/^(chrome|edge|about|chrome-extension|devtools|view-source):/.test(tab.url)) return null
      try {
        return await chrome.tabs.sendMessage<Msg, PageContext>(tab.id, { type: 'getPageContext' })
      } catch {
        return null
      }
    }

    case 'cloudPull': {
      try {
        await pullFromCloud({ force: true }) // user-triggered refresh — bypass the wake throttle
        return { ok: true }
      } catch (e) {
        return { error: e instanceof Error ? e.message : String(e) }
      }
    }

    case 'fillAssist': {
      const settings = await store.get('settings')
      if (!settings.accountEmail || msg.fields.length + msg.verify.length === 0) {
        return { results: [], corrections: [] }
      }
      try {
        return await cloudFillAssist(settings, msg.fields, msg.verify)
      } catch (e) {
        return { error: e instanceof Error ? e.message : String(e) }
      }
    }

    case 'addPhrasing': {
      // The AI recognized a field as a rephrasing of a known answer — record
      // the phrasing so the free deterministic matcher hits it next time.
      const norm = normalizeQuestion(msg.savedQuestion)
      await store.update('answerBank', (bank) =>
        bank.map((a) =>
          (a.questionNorm === norm || a.questionRaw.includes(msg.savedQuestion)) &&
          !a.questionRaw.includes(msg.phrasing)
            ? { ...a, questionRaw: [...a.questionRaw, msg.phrasing] }
            : a,
        ),
      )
      return { ok: true }
    }
  }
}

/**
 * Rewrite a just-saved answer into a clean sentence via the cloud (mini model,
 * free). Only stores the polish if the raw answer hasn't changed meanwhile;
 * options/booleans are never polished (their value must match the form).
 */
/**
 * Uploaded-CV intake: ask the cloud what roles the CV targets (tags) and what
 * facts it holds that the profile lacks. Merging is strictly additive — the
 * profile is never overwritten, only filled in. Fire and forget.
 */
async function intakeResume(resumeId: string): Promise<void> {
  const [settings, resumes] = await Promise.all([store.get('settings'), store.get('resumes')])
  if (!settings.accountEmail) return
  const r = resumes.find((x) => x.id === resumeId)
  if (!r) return
  try {
    const facts = await cloudResumeIntake(settings, r.dataBase64)
    if (facts.tags.length) {
      await store.update('resumes', (list) =>
        list.map((x) => (x.id === resumeId && x.tags.length === 0 ? { ...x, tags: facts.tags } : x)),
      )
    }
    await store.update('profile', (p) => applyIntakeFacts(p, facts))
  } catch (e) {
    console.warn('[shortlisted] resume intake failed:', e)
  }
}

async function polishInBackground(questionNorm: string, questionRaw: string, answer: string): Promise<void> {
  try {
    const settings = await store.get('settings')
    if (!settings.accountEmail) return
    const bank = await store.get('answerBank')
    // Same match rule as saveAnswer (exact or fuzzy) — the entry's own norm
    // may differ from this phrasing's.
    const entry = bank.find((a) => a.questionNorm === questionNorm || similarity(a.questionNorm, questionNorm) >= 0.92)
    if (!entry || entry.answer !== answer || entry.polished) return
    const polished = await polishAnswer(settings, questionRaw, answer)
    if (!polished) return
    await store.update('answerBank', (b) =>
      b.map((a) => (a.id === entry.id && a.answer === answer ? { ...a, polished } : a)),
    )
  } catch (e) {
    console.error('[shortlisted] polish failed (answer kept as written):', e)
  }
}

function sameJob(a: string, b: string): boolean {
  try {
    const ua = new URL(a)
    const ub = new URL(b)
    return ua.hostname === ub.hostname && ua.pathname.replace(/\/$/, '') === ub.pathname.replace(/\/$/, '')
  } catch {
    return a === b
  }
}

